import { generateCodeVerifier, generateCodeChallenge, generateState } from "./pkce.ts";
import { KickOAuthSessionStore, AccountStore } from "../db/index.ts";
import { connectionManager } from "../ws/connection-manager.ts";
import { subscribeKickEvents } from "./kick-subscriptions.ts";
import { config } from "../config.ts";
import { logger } from "@twirchat/shared/logger";
import type { KickBuildUrlResponse, KickExchangeResponse } from "@twirchat/shared";

const log = logger("kick-auth");

const KICK_AUTH_URL = "https://id.kick.com/oauth/authorize";
const KICK_TOKEN_URL = "https://id.kick.com/oauth/token";

interface KickTokenResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  token_type: string;
  scope: string;
}

interface KickUserResponse {
  data: {
    user_id: number;
    name: string;
    email?: string;
    profile_picture?: string;
  }[];
  message: string;
}

/**
 * Build a Kick OAuth authUrl using a codeChallenge + state generated by the desktop.
 * This is the new HTTP-based flow (replaces startKickOAuth for desktop auth).
 */
export function buildKickAuthUrl(
  codeChallenge: string,
  state: string,
  redirectUri: string,
): KickBuildUrlResponse {
  const params = new URLSearchParams({
    client_id: config.KICK_CLIENT_ID,
    redirect_uri: redirectUri,
    response_type: "code",
    scope: "user:read channel:read chat:write events:subscribe",
    state,
    code_challenge: codeChallenge,
    code_challenge_method: "S256",
  });

  return { url: `${KICK_AUTH_URL}?${params.toString()}` };
}

/**
 * Exchange an authorization code for tokens.
 * The desktop provides the codeVerifier it generated during PKCE setup.
 */
export async function exchangeKickCode(
  code: string,
  codeVerifier: string,
  redirectUri: string,
): Promise<KickExchangeResponse> {
  const res = await fetch(KICK_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      client_id: config.KICK_CLIENT_ID,
      client_secret: config.KICK_CLIENT_SECRET,
      redirect_uri: redirectUri,
      code,
      code_verifier: codeVerifier,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Kick token exchange failed: ${res.status} ${body}`);
  }

  const data = (await res.json()) as {
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
    scope?: string;
  };

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
    scope: data.scope ? data.scope.split(" ") : [],
  };
}

/**
 * Legacy: Start Kick OAuth flow (WebSocket-based, stores session in DB).
 * Used for backend-managed auth flow.
 */
export async function startKickOAuth(clientSecret: string): Promise<string> {
  const codeVerifier = generateCodeVerifier();
  const codeChallenge = generateCodeChallenge(codeVerifier);
  const state = generateState();

  await KickOAuthSessionStore.create({ state, clientSecret, codeVerifier });

  const params = new URLSearchParams({
    client_id: config.KICK_CLIENT_ID,
    redirect_uri: config.KICK_REDIRECT_URI,
    response_type: "code",
    scope: "user:read channel:read chat:write",
    state,
    code_challenge: codeChallenge,
    code_challenge_method: "S256",
  });

  return `${KICK_AUTH_URL}?${params.toString()}`;
}

export async function refreshKickToken(
  refreshToken: string,
): Promise<{ accessToken: string; refreshToken?: string; expiresIn?: number }> {
  const res = await fetch(KICK_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      client_id: config.KICK_CLIENT_ID,
      client_secret: config.KICK_CLIENT_SECRET,
      refresh_token: refreshToken,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Kick token refresh failed: ${res.status} ${body}`);
  }

  const data = (await res.json()) as {
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
  };

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
  };
}

export async function handleKickCallback(
  code: string,
  state: string
): Promise<void> {
  const session = await KickOAuthSessionStore.consume(state);
  if (!session) {
    throw new Error("Invalid or expired OAuth state");
  }

  // Exchange code for tokens
  const tokenRes = await fetch(KICK_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      client_id: config.KICK_CLIENT_ID,
      client_secret: config.KICK_CLIENT_SECRET,
      redirect_uri: config.KICK_REDIRECT_URI,
      code,
      code_verifier: session.codeVerifier,
    }),
  });

  if (!tokenRes.ok) {
    const body = await tokenRes.text();
    throw new Error(`Kick token exchange failed: ${tokenRes.status} ${body}`);
  }

  const tokens = (await tokenRes.json()) as KickTokenResponse;

  // Fetch user info
  const userRes = await fetch("https://api.kick.com/public/v1/user", {
    headers: {
      Authorization: `Bearer ${tokens.access_token}`,
      "Client-ID": config.KICK_CLIENT_ID,
    },
  });

  if (!userRes.ok) {
    throw new Error(`Failed to fetch Kick user: ${userRes.status}`);
  }

  const user = (await userRes.json()) as KickUserResponse;
  const userData = user.data[0];
  if (!userData) {
    throw new Error("Kick user info response empty");
  }

  const tokenExpiresAt = new Date(Date.now() + tokens.expires_in * 1000);
  const scopes = tokens.scope ? tokens.scope.split(" ") : [];

  // Persist account in Postgres
  await AccountStore.upsert({
    clientSecret: session.clientSecret,
    platform: "kick",
    platformUserId: String(userData.user_id),
    username: userData.name,
    displayName: userData.name,
    avatarUrl: userData.profile_picture,
    accessToken: tokens.access_token,
    refreshToken: tokens.refresh_token,
    tokenExpiresAt,
    scopes,
  });

  // Subscribe to Kick webhook events for this user's channel
  try {
    await subscribeKickEvents(tokens.access_token, config.KICK_CLIENT_ID);
  } catch (err) {
    log.error("Failed to subscribe to Kick events", { err: String(err) });
    // Non-fatal: auth still succeeded; events subscription can be retried later
  }

  // Push auth_success to desktop via WS
  connectionManager.send(session.clientSecret, {
    type: "auth_success",
    platform: "kick",
    username: userData.name,
    displayName: userData.name,
  });
}
