/**
 * Twitch OAuth helpers — backend side.
 *
 * The PKCE session (state + codeVerifier) lives in-memory on the desktop.
 * Backend is responsible only for:
 *   1. Assembling the Twitch authUrl given a codeChallenge + state
 *   2. Exchanging an auth code for tokens (code + codeVerifier → tokens)
 *   3. Refreshing tokens (refreshToken → new tokens)
 *
 * Tokens are returned to the desktop and stored in its local SQLite.
 */

import { config } from "../config.ts";
import { TWITCH_AUTH_URL, TWITCH_TOKEN_URL } from "@twirchat/shared";
import type {
  TwitchBuildUrlResponse,
  TwitchExchangeResponse,
  TwitchRefreshResponse,
} from "@twirchat/shared";

const TWITCH_SCOPES = [
  "chat:read",
  "chat:edit",
  "channel:read:subscriptions",
  "channel:read:redemptions",
  "moderator:read:followers",
  "bits:read",
  "channel:manage:broadcast",
];

/**
 * Build a Twitch OAuth authUrl using a codeChallenge + state generated by the desktop.
 */
export function buildTwitchAuthUrl(
  codeChallenge: string,
  state: string,
  redirectUri: string,
): TwitchBuildUrlResponse {
  const params = new URLSearchParams({
    client_id: config.TWITCH_CLIENT_ID,
    redirect_uri: redirectUri,
    response_type: "code",
    scope: TWITCH_SCOPES.join(" "),
    state,
    code_challenge: codeChallenge,
    code_challenge_method: "S256",
  });

  return { url: `${TWITCH_AUTH_URL}?${params.toString()}` };
}

/**
 * Exchange an authorization code for tokens.
 * The desktop provides the codeVerifier it generated during PKCE setup.
 */
export async function exchangeTwitchCode(
  code: string,
  codeVerifier: string,
  redirectUri: string,
): Promise<TwitchExchangeResponse> {
  const res = await fetch(TWITCH_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      client_id: config.TWITCH_CLIENT_ID,
      client_secret: config.TWITCH_CLIENT_SECRET,
      redirect_uri: redirectUri,
      code,
      code_verifier: codeVerifier,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Twitch token exchange failed: ${res.status} ${body}`);
  }

  const data = (await res.json()) as {
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
    scope?: string[];
  };

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
    scope: data.scope,
  };
}

/**
 * Refresh a Twitch access token using a refresh token.
 */
export async function refreshTwitchToken(
  refreshToken: string,
): Promise<TwitchRefreshResponse> {
  const res = await fetch(TWITCH_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      client_id: config.TWITCH_CLIENT_ID,
      client_secret: config.TWITCH_CLIENT_SECRET,
      refresh_token: refreshToken,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`Twitch token refresh failed: ${res.status} ${body}`);
  }

  const data = (await res.json()) as {
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
  };

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
  };
}
