/**
 * YouTube OAuth helpers — backend side.
 *
 * The PKCE session (state + codeVerifier) lives in-memory on the desktop.
 * Backend is responsible only for:
 *   1. Assembling the YouTube authUrl given a codeChallenge + state
 *   2. Exchanging an auth code for tokens (code + codeVerifier → tokens)
 *   3. Refreshing tokens (refreshToken → new tokens)
 *
 * Tokens are returned to the desktop and stored in its local SQLite.
 */

import { config } from "../config.ts";
import { YOUTUBE_AUTH_URL, YOUTUBE_TOKEN_URL } from "@twirchat/shared";
import type {
  YouTubeBuildUrlResponse,
  YouTubeExchangeResponse,
  YouTubeRefreshResponse,
} from "@twirchat/shared";

const YOUTUBE_SCOPES = [
  "openid",
  "profile",
  "https://www.googleapis.com/auth/youtube.readonly",
  "https://www.googleapis.com/auth/youtube.force-ssl",
];

/**
 * Build a YouTube OAuth authUrl using a codeChallenge + state generated by the desktop.
 */
export function buildYouTubeAuthUrl(
  codeChallenge: string,
  state: string,
  redirectUri: string,
): YouTubeBuildUrlResponse {
  const params = new URLSearchParams({
    client_id: config.YOUTUBE_CLIENT_ID,
    redirect_uri: redirectUri,
    response_type: "code",
    scope: YOUTUBE_SCOPES.join(" "),
    state,
    code_challenge: codeChallenge,
    code_challenge_method: "S256",
    access_type: "offline",
    prompt: "consent",
  });

  return { url: `${YOUTUBE_AUTH_URL}?${params.toString()}` };
}

/**
 * Exchange an authorization code for tokens.
 * The desktop provides the codeVerifier it generated during PKCE setup.
 */
export async function exchangeYouTubeCode(
  code: string,
  codeVerifier: string,
  redirectUri: string,
): Promise<YouTubeExchangeResponse> {
  const res = await fetch(YOUTUBE_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      client_id: config.YOUTUBE_CLIENT_ID,
      client_secret: config.YOUTUBE_CLIENT_SECRET,
      redirect_uri: redirectUri,
      code,
      code_verifier: codeVerifier,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`YouTube token exchange failed: ${res.status} ${body}`);
  }

  const data = (await res.json()) as {
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
    scope?: string;
  };

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
    scope: data.scope ? data.scope.split(" ") : [],
  };
}

/**
 * Refresh a YouTube access token using a refresh token.
 */
export async function refreshYouTubeToken(
  refreshToken: string,
): Promise<YouTubeRefreshResponse> {
  const res = await fetch(YOUTUBE_TOKEN_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "refresh_token",
      client_id: config.YOUTUBE_CLIENT_ID,
      client_secret: config.YOUTUBE_CLIENT_SECRET,
      refresh_token: refreshToken,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    throw new Error(`YouTube token refresh failed: ${res.status} ${body}`);
  }

  const data = (await res.json()) as {
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
  };

  return {
    accessToken: data.access_token,
    refreshToken: data.refresh_token,
    expiresIn: data.expires_in,
  };
}
